"""add sleep_logs and activity_logs

Revision ID: 17a33b215cdb
Revises: cf001fb38aa6
Create Date: 2026-07-24 14:24:32.652189

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '17a33b215cdb'
down_revision: str | None = 'cf001fb38aa6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('external_activity_id', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('external_activity_id')
    )
    op.create_table('sleep_logs',
    sa.Column('external_log_id', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('efficiency', sa.Integer(), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('external_log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sleep_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
