"""add forecast_runs table

Revision ID: 25f6b8b6dd04
Revises: 9d147f1e6c93
Create Date: 2026-08-01 13:44:18.987133

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '25f6b8b6dd04'
down_revision: str | None = '9d147f1e6c93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('target_metric', sa.String(length=50), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('n_test_folds', sa.Integer(), nullable=False),
    sa.Column('model_mae', sa.Float(), nullable=True),
    sa.Column('baseline_mae', sa.Float(), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
