"""drop ai_insights title column

Revision ID: 9d147f1e6c93
Revises: 4e98e62d29b1
Create Date: 2026-07-30 14:41:57.052166

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9d147f1e6c93'
down_revision: str | None = '4e98e62d29b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_insights', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_insights', sa.Column('title', sa.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
