"""initial schema

Revision ID: cf001fb38aa6
Revises: 
Create Date: 2026-07-24 13:33:37.818177

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cf001fb38aa6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=True),
    sa.Column('calories_total', sa.Integer(), nullable=True),
    sa.Column('calories_bmr', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('hrv_rmssd_avg', sa.Float(), nullable=True),
    sa.Column('spo2_avg', sa.Float(), nullable=True),
    sa.Column('spo2_min', sa.Float(), nullable=True),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_efficiency', sa.Integer(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('readiness_source', sa.String(length=30), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'provider')
    )
    op.create_table('oauth_tokens',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('scope', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('sync_state',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('last_synced_date', sa.Date(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('cursor', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('provider', 'metric_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_table('oauth_tokens')
    op.drop_table('daily_metrics')
    # ### end Alembic commands ###
