"""add model comparison fields to forecast_runs

Revision ID: d4741dbc36ea
Revises: 25f6b8b6dd04
Create Date: 2026-08-01 15:37:10.776537

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd4741dbc36ea'
down_revision: str | None = '25f6b8b6dd04'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_runs', sa.Column('winning_model', sa.String(length=50), nullable=True))
    op.add_column('forecast_runs', sa.Column('candidate_results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_runs', 'candidate_results')
    op.drop_column('forecast_runs', 'winning_model')
    # ### end Alembic commands ###
